---
- hosts: default
  vars:
    timezone: "Asia/Tokyo"
    log_dir: "/var/log/locust"
  tasks:
    - block:
      - block:
        - name: Check timezone
          shell: timedatectl | grep -e {{ timezone }}
          register: timedatectl_timezone
          check_mode: no
          changed_when: false
          failed_when: false
        - name: Set timezone
          shell: timedatectl set-timezone {{ timezone }}
          when: timedatectl_timezone.stdout == ""
      - block:
        - name: Upgrade all packages
          apt:
            upgrade: yes
            update_cache: yes
        - name: Install the package "python3-pip"
          apt:
            name: python3-pip
            state: present
        - name: Install the package "locust"
          pip:
            name: locust
            executable: pip3
      - block:
        - name: Create locust logging directory
          file: path={{ log_dir }} state=directory owner=vagrant group=vagrant mode=0755
      become: true
